/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Assignment_4;

/**
 *
 * @author Omar
 */
public class A4_Q10 extends javax.swing.JFrame {

    /**
     * Creates new form A4_Q10
     */
    public A4_Q10() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        degreesFahrenheitTextField = new javax.swing.JTextField();
        degreesCelsiusTextField = new javax.swing.JTextField();
        fahrenheitToCelsiusButton = new javax.swing.JButton();
        celsiusToFahrenheitButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Temperature Converter");

        degreesFahrenheitTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degreesFahrenheitTextFieldActionPerformed(evt);
            }
        });

        degreesCelsiusTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degreesCelsiusTextFieldActionPerformed(evt);
            }
        });

        fahrenheitToCelsiusButton.setText("F --> C");
        fahrenheitToCelsiusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fahrenheitToCelsiusButtonActionPerformed(evt);
            }
        });

        celsiusToFahrenheitButton.setText("C --> F");
        celsiusToFahrenheitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celsiusToFahrenheitButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Degrees Fahrenheit:");

        jLabel2.setText("Degrees Celsius:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(degreesCelsiusTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(degreesFahrenheitTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fahrenheitToCelsiusButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(celsiusToFahrenheitButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(degreesFahrenheitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fahrenheitToCelsiusButton)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(degreesCelsiusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(celsiusToFahrenheitButton)
                    .addComponent(jLabel2))
                .addContainerGap(185, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void degreesCelsiusTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degreesCelsiusTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_degreesCelsiusTextFieldActionPerformed

    private void fahrenheitToCelsiusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fahrenheitToCelsiusButtonActionPerformed
        //Use the Fahrenheit value entered in the text field and
        String degreesFahrenheitString = degreesFahrenheitTextField.getText();

        double degreesFahrenheit = Double.parseDouble(degreesFahrenheitString);

        //perform a conversion calculation from Fahrenheit to Celsius.
        
        double degreesCelsius = (degreesFahrenheit - 32) * 5 / 9;
        
        degreesCelsius = Math.round(degreesCelsius * 100);

        degreesCelsius = degreesCelsius / 100;

        //The end result will be a display of the corresponding Celsius temperature.
        String degreesCelsiusText = Double.toString(degreesCelsius);

        degreesCelsiusTextField.setText(degreesCelsiusText);
    }//GEN-LAST:event_fahrenheitToCelsiusButtonActionPerformed

    private void celsiusToFahrenheitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celsiusToFahrenheitButtonActionPerformed
        //Use the Celsius value entered in the text field and 
        String degreesCelsiusString = degreesCelsiusTextField.getText();

        double degreesCelsius = Double.parseDouble(degreesCelsiusString);

        //perform a conversion calculation from Celsius to Fahrenheit

        double degreesFahrenheit = degreesCelsius * 1.8 + 32;
        
        degreesFahrenheit = Math.round(degreesFahrenheit * 100);

        degreesFahrenheit = degreesFahrenheit / 100;

        //This time, the end result will be a display of the corresponding Fahrenheit temperature. 
        String degreesFahrenheitText = Double.toString(degreesFahrenheit);

        degreesFahrenheitTextField.setText(degreesFahrenheitText);
    }//GEN-LAST:event_celsiusToFahrenheitButtonActionPerformed

    private void degreesFahrenheitTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degreesFahrenheitTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_degreesFahrenheitTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(A4_Q10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(A4_Q10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(A4_Q10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(A4_Q10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new A4_Q10().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton celsiusToFahrenheitButton;
    private javax.swing.JTextField degreesCelsiusTextField;
    private javax.swing.JTextField degreesFahrenheitTextField;
    private javax.swing.JButton fahrenheitToCelsiusButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
